In [9]:
import numpy as np

In [12]:
array1=np.array([[1,2,3],[4,5,6]])
np.sum(array1)

np.int64(21)

In [13]:
np.sum(array1,axis=0)

array([5, 7, 9])

In [14]:
array1.ndim

2

In [15]:
np.prod(array1)

np.int64(720)

In [16]:
array1.prod(axis=0)

array([ 4, 10, 18])

In [17]:
array1.prod(axis=-1)

array([  6, 120])

In [18]:
array1.min()

np.int64(1)

In [19]:
array1.min(axis=1)

array([1, 4])

In [20]:
array1.max()

np.int64(6)

In [21]:
array1.argmin()

np.int64(0)

In [22]:
array1.argmin(axis=1)

array([0, 0])

In [23]:
array1.argmax(axis=1)

array([2, 2])

In [24]:
array1.mean()

np.float64(3.5)

In [25]:
array1.mean(axis=1)

array([2., 5.])

In [26]:
array1.std()

np.float64(1.707825127659933)

In [27]:
array1.var()

np.float64(2.9166666666666665)

In [28]:
array1.clip(2,3)

array([[2, 2, 3],
       [3, 3, 3]])

In [29]:
array2=np.array([1.2,2.4,3.6])
np.around(array2)

array([1., 2., 4.])

In [30]:
array2.round(decimals=1)

array([1.2, 2.4, 3.6])