保存numpy数据

In [1]:
import numpy as np

In [10]:
x=np.arange(0,10,dtype=np.int16).reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16)

In [13]:
np.savetxt("jwd.txt", x,fmt="%d",delimiter=";")

读写array结构

In [15]:
x=np.arange(0,10,dtype=np.int16).reshape((2,5))
np.save("jwd.npy",x)

In [16]:
y=np.load("jwd.npy")
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16)

In [17]:
x=np.arange(0,10,dtype=np.int16).reshape((2,5))
y=np.arange(10,20,dtype=np.int16).reshape((2,5))
np.savez("jwd.npz",x=x,y=y)

In [18]:
a=np.load("jwd.npz")
a.keys()

KeysView(NpzFile 'jwd.npz' with keys: x, y)

In [19]:
a["x"]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16)

In [20]:
a["y"]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int16)