随机模块

In [1]:
import numpy as np

In [2]:
# 随机值都是从0到1的均匀分布
np.random.rand(3,2)

array([[0.45281232, 0.21965599],
       [0.10437487, 0.73691308],
       [0.41290906, 0.21237983]])

In [3]:
np.random.randint(0,10,size=(5,4))

array([[6, 1, 6, 5],
       [5, 7, 1, 8],
       [3, 8, 3, 1],
       [2, 2, 9, 1],
       [6, 7, 4, 6]], dtype=int32)

In [4]:
np.random.rand()

0.04069806825074995

In [5]:
np.random.random_sample ()

0.9457285160764606

In [6]:
np.random.randint(0,10,3)

array([8, 0, 5], dtype=int32)

In [7]:
mu,sigma=0,0.1
np.random.normal(mu,sigma,size=(5,4))

array([[-0.00113413, -0.05233024,  0.06759074,  0.08710218],
       [ 0.06699717,  0.23861332,  0.10635881, -0.13527   ],
       [ 0.0083157 , -0.05081076, -0.11100749, -0.10118829],
       [ 0.02893567, -0.19116616,  0.11033713, -0.11021675],
       [-0.02258274,  0.06039764, -0.04427338, -0.08781812]])

In [8]:
np.set_printoptions(precision=2)

In [9]:
np.random.normal(mu,sigma,size=(5,4))

array([[ 0.01, -0.07,  0.12, -0.17],
       [ 0.12, -0.17, -0.05, -0.02],
       [-0.09,  0.06, -0.09, -0.05],
       [-0.12,  0.02, -0.04,  0.02],
       [-0.1 ,  0.22,  0.03,  0.1 ]])

洗牌

In [10]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.shuffle(x)

In [12]:
x

array([3, 9, 7, 4, 5, 6, 8, 2, 0, 1])

随机种子

In [15]:
np.random.seed(0)
mu,sigma=0,0.1
np.random.normal(mu,sigma,size=(5,4))

array([[ 0.18,  0.04,  0.1 ,  0.22],
       [ 0.19, -0.1 ,  0.1 , -0.02],
       [-0.01,  0.04,  0.01,  0.15],
       [ 0.08,  0.01,  0.04,  0.03],
       [ 0.15, -0.02,  0.03, -0.09]])