In [2]:
#排序

In [3]:
import numpy as np

In [4]:
array1=np.array([[1,5,1,3,2],[2,3,4,5,6]],dtype=np.int32)
np.sort(array1)

array([[1, 1, 2, 3, 5],
       [2, 3, 4, 5, 6]], dtype=int32)

In [5]:
np.sort(array1,axis=0)

array([[1, 3, 1, 3, 2],
       [2, 5, 4, 5, 6]], dtype=int32)

In [6]:
np.argsort(array1)

array([[0, 2, 4, 3, 1],
       [0, 1, 2, 3, 4]])

In [10]:
array2=np.linspace(0,10,10)

In [11]:
array2

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [12]:
values=np.array([2.5,6.5,9.5])
np.searchsorted(array2,values)

array([3, 6, 9])

In [15]:
array3=np.array([[1,0,6],
                 [1,7,0],
                 [2,3,1],
                 [2,4,0]])
array3

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [17]:
index = np.lexsort((-1 * array3[:, 0], array3[:, 2]))
index

array([3, 1, 2, 0])

In [18]:
array3[index]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])