读写文件

In [1]:
import numpy as np

In [2]:
%%writefile jwd.txt
1 2 3 4 5 6
2 3 4 5 6 7

Writing jwd.txt


In [3]:
data=np.loadtxt("jwd.txt")

In [4]:
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

In [5]:
%%writefile jwd.txt
1,2,3,4,5,6
2,3,4,5,6,7

Overwriting jwd.txt


In [6]:
data=np.loadtxt("jwd.txt",delimiter=",")

In [7]:
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

In [8]:
%%writefile jwd.txt
x,y, z, a, b
1,2,3,4,5
2,3,4,5,6

Overwriting jwd.txt


In [9]:
data=np.loadtxt("jwd.txt",delimiter=",",skiprows=1)
data

array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])