运算

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.multiply(x,y)

array([ 4, 10, 18])

In [3]:
np.dot(x,y)

np.int64(32)

In [4]:
x=np.array([[1,2],[1,2]])
y=np.array([[1,2,3],[1,2,3]])
np.dot(x,y)

array([[3, 6, 9],
       [3, 6, 9]])

逻辑运算

In [5]:
x=np.array([1,2,3])
y=np.array([1,1,1])
x== y

array([ True, False, False])

In [6]:
y=np.array([1,0,3])
np.logical_and(x,y)

array([ True, False,  True])

In [8]:
np.logical_not(y)

array([False,  True, False])

In [9]:
np.logical_or(x,y)

array([ True,  True,  True])