数组形状

数组形状操作

In [1]:
import numpy as np

In [5]:
array1=np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array1.shape

(10,)

In [7]:
array1.shape=2,5
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
array1.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小不能改变

In [9]:
array1[np.newaxis,:]

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [10]:
array1.squeeze()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array1.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [13]:
array1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [14]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

数组的连接

In [15]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [16]:
c=np.concatenate((a,b))

In [17]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
c=np.concatenate((a,b),axis=0)

In [20]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [24]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])